name: Update PR Count

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_pr_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Open PR Count
        run: echo "OPEN_PR_COUNT=$(gh pr list --repo ${{ github.repository }} --state open --json number --jq 'length')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Closed PR Count
        run: echo "CLOSED_PR_COUNT=$(gh pr list --repo ${{ github.repository }} --state closed --json number --jq 'length')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Total PRs
        run: echo "TOTAL_PR_COUNT=$(( $OPEN_PR_COUNT + $CLOSED_PR_COUNT ))" >> $GITHUB_ENV

      - name: Create JSON File
        run: |
          echo '{ "schemaVersion": 1, "label": "Total PRs", "message": "'$TOTAL_PR_COUNT'", "color": "blue" }' > pr-count.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pr-count.json
          git commit -m "Updated PR count"
          git push
        continue-on-error: true  # Prevent errors if no changes are made
