name: Update PR Count

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_pr_count:
    permissions:
      contents: write
      pull-requests: read 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Open PR Count
        run: echo "OPEN_PR_COUNT=$(gh pr list --repo ${{ github.repository }} --state open --json number --jq 'length')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Closed PR Count
        run: echo "CLOSED_PR_COUNT=$(gh pr list --repo ${{ github.repository }} --state closed --json number --jq 'length')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Total PRs
        run: echo "TOTAL_PR_COUNT=$(( $OPEN_PR_COUNT + $CLOSED_PR_COUNT ))" >> $GITHUB_ENV

      - name: Create JSON File
        run: |
          echo '{ "schemaVersion": 1, "label": "Total PRs", "message": "'$TOTAL_PR_COUNT'", "color": "blue" }' > pr-count.json

      - name: Commit and push changes
        run: |
            git add pr-count.json
            if git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
            fi
            git commit -m "Update PR count"
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug JSON File
        run: cat pr-count.json
          
      
        
